from dataclasses import dataclass
from datetime import datetime
from typing import List, Any

@dataclass
class ClassCalendar:
    sequence_number: int
    school_code: int
    academic_year: str
    short_title: str
    description: str


@dataclass
class FlexPeriod:
    sequence_number: int
    school_code: int
    academic_year: str
    short_title: str
    description: str
    start_time: datetime
    end_time: datetime
    type_code: str


@dataclass
class ClassSchedule:
    student_id: int
    school_code: int
    sequence_number: int
    section_number: int
    course_id: str
    date_started: datetime
    date_ended: datetime

@dataclass
class Roster:
    List: ClassSchedule


@dataclass
class Course:
    vocational_education_subject_area_code: str
    vocational_education_course_level_code: str
    course_level_code: str
    course_type_code: str
    next_course: str
    term_sequence: int
    year_sequence: int
    traditional_gender: str
    nclb_core_code: str
    nclb_core_area1_code: str
    nclb_core_area2_code: str
    content_group_code: str
    nces_code: str
    cip_code: str
    board_adoption_date: None
    last_revision_date: None
    revision_type_code: str
    inactive_date: None
    academic_weight: int
    meets_algebra_i_requirement: bool
    algebra_i_credit_required: int
    service_id_code: str
    population_served_code: str
    class_type_code: str
    course_sequence_code: str
    non_campus_based_instruction_code: str
    on_ramps_dual_enrollment_indicator: str
    include_for_extracurricular_activity_eligibility_indicator: str
    hours_for_completion: int
    cost_of_course: int
    content_subcategory_code: str
    standards_grade_range_code: str
    content_standards_alignment_code: str
    charter_non_core_indicator: str
    advanced_course_state_code: str
    college_state_course_code: str
    middle_school_core_indicator: str
    correspondence_language_code1: str
    title_for_language1: str
    correspondence_language_code2: str
    title_for_language2: str
    correspondence_language_code3: str
    title_for_language3: str
    correspondence_language_code4: str
    title_for_language4: str
    correspondence_language_code5: str
    title_for_language5: str
    correspondence_language_code6: str
    title_for_language6: str
    user_code1: str
    user_code2: str
    user_code3: str
    user_code4: str
    user_code5: str
    user_code6: str
    user_code7: str
    user_code8: str
    id: str
    title: str
    long_description: str
    notes: str
    content_description: str
    non_academic_or_honors_code: str
    subject_area1_code: str
    subject_area2_code: str
    subject_area3_code: str
    department_code: str
    state_course_code: int
    csf_course_list: str
    college_prep_indicator_code: str
    credit_default: int
    credit_max: int
    term_type_code: str
    low_grade: int
    high_grade: int
    csu_subject_area_code: str
    csu_rule_can_be_an_elective: str
    csu_rule_honors_code: str
    csu_rule_validation_level_code: str
    uc_subject_area_code: str
    uc_rule_can_be_an_elective: str
    uc_rule_honors_code: str
    uc_rule_validation_level_code: int
    teacher_aide_indicator: bool
    physical_education_indicator: bool
    inactive_status_code: str
    prerequisite_course: str
    alternate_course: str
    default_max_students: int
    next_year_inactive_status_code: str


@dataclass
class SectionStaffMember:
    staff_id: int
    last_name: str
    first_name: str
    is_primary_teacher: bool
    staff_role_code: str
    teacher_position_code: str
    attendance_permission: str
    gradebook_permission_code: str
    grade_reporting_access: str
    student_access: str
    include_in_state_reporting: str
    start_date: None
    end_date: None
    inactive_status_code: str


@dataclass
class Section:
    school_code: int
    section_number: int
    period: int
    period_block: int
    semester: str
    class_calendar: str
    course_id: int
    section_staff_members: List[SectionStaffMember]
    room: str
    credit: int
    gender_restriction: str
    low_grade: int
    high_grade: int
    max_students: int
    total_students: int
    total_boys: int
    total_girls: int
    total_other_gender: int
    inactive_status_code: str
    program_code: str
    hourly_attendance_program_code: str
    exclusion_code: str
    counts_for_ada: str
    multi_teacher_code: str
    scheduling_group: str
    team_course_group: str
    team_number: int
    semester_group: str
    track: str
    class_id: int
    education_service_code: str
    language_of_instruction_code: str
    instructional_strategy_code: str
    funding_source_code: str
    career_technical_education_provider_code: str
    independent_study_indicator: str
    distance_learning_indicator: str
    itinerant_teacher_indicator: str
    use_supplemental_attendance: bool
    articulated_course_indicator: str
    non_campus_based_instruction_code: str
    population_served_code: str
    class_type_code: str
    monthly_minutes: int
    pre_k_school_type_code: str
    pre_k_curricula_code: str
    is_high_quality_pre_k_program: bool
    instruction_type_code: str
    program_evaluation_type_code: str
    educational_environment_code: str
    career_technical_education_hours: int
    content_subcategory_code: str
    charter_non_core_indicator: str
    advanced_course_state_code: str
    online_instruction_type_code: str
    middle_school_core_indicator: str
    non_credentialed_authorization_code: str
    high_quality_career_technical_education_indicator: str
    user_code1: str
    user_code2: str
    user_code3: str
    user_code4: str
    user_code5: str
    user_code6: str
    user_code7: str
    user_code8: str
    primary_class: bool


@dataclass
class MasterScheduleSection:
    school_code: int
    section_number: int
    period: int
    period_block: int
    semester: str
    class_calendar: str
    course_id: str
    section_staff_members: List[Any]
    room: str
    credit: int
    gender_restriction: str
    low_grade: int
    high_grade: int
    max_students: int
    total_students: int
    total_boys: int
    total_girls: int
    total_other_gender: int
    total_prescheduled: int
    inactive_status_code: str
    program_code: str
    hourly_attendance_program_code: str
    exclusion_code: str
    counts_for_ada: str
    multi_teacher_code: int
    scheduling_group: str
    team_course_group: str
    team_number: int
    semester_group: str
    track: str
    class_id: int
    education_service_code: str
    language_of_instruction_code: str
    instructional_strategy_code: str
    funding_source_code: str
    career_technical_education_provider_code: str
    independent_study_indicator: str
    distance_learning_indicator: str
    itinerant_teacher_indicator: str
    use_supplemental_attendance: bool
    articulated_course_indicator: str
    non_campus_based_instruction_code: str
    population_served_code: str
    class_type_code: str
    monthly_minutes: int
    pre_k_school_type_code: str
    pre_k_curricula_code: str
    is_high_quality_pre_k_program: bool
    instruction_type_code: str
    program_evaluation_type_code: str
    educational_environment_code: str
    career_technical_education_hours: int
    content_subcategory_code: str
    charter_non_core_indicator: str
    advanced_course_state_code: str
    online_instruction_type_code: str
    middle_school_core_indicator: str
    non_credentialed_authorization_code: str
    high_quality_career_technical_education_indicator: str
    arena_scheduling_indicator: str
    exclude_from_scheduler: bool
    flex_period_sequence_number: int
    class_calendar_sequence_number: int
    user_code1: str
    user_code2: str
    user_code3: str
    user_code4: str
    user_code5: str
    user_code6: str
    user_code7: str
    user_code8: str

@dataclass
class AlternateCourseRequest:
    student_id: int
    school_code: int
    sequence_number: int
    course_id: str
    priority_sort_order: int


@dataclass
class CourseRequest:
    student_id: int
    alternate_course_requests: List[AlternateCourseRequest]
    actual_primary_course_id: str
    school_code: int
    sequence_number: int
    section_number: int
    course_id: str
    preferred_teacher_number: int
    reject_code: str
    alternate_tag: str
    permanent_lock_code: str
